apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nfss.edgefs.rook.io
spec:
  group: edgefs.rook.io
  names:
    kind: NFS
    listKind: NFSList
    plural: nfss
    singular: nfs
  scope: Namespaced
  version: v1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            instances:
              type: integer
              minimum: 1
          required:
            - instances
  additionalPrinterColumns:
    - name: Instances
      type: string
      description: Edgefs's service instances count
      JSONPath: .spec.instances
