apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: s3s.edgefs.rook.io
spec:
  group: edgefs.rook.io
  names:
    kind: S3
    listKind: S3List
    plural: s3s
    singular: s3
  scope: Namespaced
  version: v1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            instances:
              type: integer
              minimum: 1
          required:
            - instances
  additionalPrinterColumns:
    - name: Instances
      type: string
      description: Edgefs's service instances count
      JSONPath: .spec.instances
