apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusters.edgefs.rook.io
spec:
  group: edgefs.rook.io
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  scope: Namespaced
  version: v1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            edgefsImageName:
              type: string
            dataDirHostPath:
              pattern: ^/(\S+)
              type: string
            devicesResurrectMode:
              pattern: ^(restore|restoreZap|restoreZapWait)$
              type: string
            dashboard:
              properties:
                localAddr:
                  type: string
            network:
              properties:
                serverIfName:
                  type: string
                brokerIfName:
                  type: string
            skipHostPrepare:
              type: boolean
            storage:
              properties:
                nodes:
                  items: {}
                  type: array
                useAllDevices: {}
                useAllNodes:
                  type: boolean
          required:
            - edgefsImageName
  additionalPrinterColumns:
    - name: Image
      type: string
      description: Edgefs target image
      JSONPath: .spec.edgefsImageName
    - name: HostPath
      type: string
      description: Directory used on the Kubernetes nodes to store Edgefs data
      JSONPath: .spec.dataDirHostPath
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
    - name: State
      type: string
      description: Current State
      JSONPath: .status.state
