compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@apollo/client@*":
    dependencies:
      react-dom: "*"
  "@testing-library/react@*":
    dependencies:
      react-dom: "*"
  react-multi-carousel@*:
    dependencies:
      react: "*"
  react-toastify@*:
    dependencies:
      react-dom: "*"
  react-transition-group@*:
    dependencies:
      react-dom: "*"
  sax@*:
    dependencies:
      buffer: "*"
      stream-browserify: "*"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
