compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

npmScopes:
  jsr:
    npmRegistryServer: "https://npm.jsr.io"

packageExtensions:
  "@apollo/client@*":
    dependencies:
      react-dom: "*"
  "@testing-library/react@*":
    dependencies:
      react-dom: "*"
  react-multi-carousel@*:
    dependencies:
      react: "*"
  react-toastify@*:
    dependencies:
      react-dom: "*"
  react-transition-group@*:
    dependencies:
      react-dom: "*"
  sax@*:
    dependencies:
      buffer: "*"
      stream-browserify: "*"

yarnPath: .yarn/releases/yarn-4.5.1.cjs
