import { builder } from "./builder"

// Side-effect imports register types with the builder
import "./schema/scalars"
import "./schema/enums"
import "./schema/inputs"
import "./schema/refs"
import "./schema/pagination"
import "./schema/analytics"
import "./schema/description"
import "./schema/files"
import "./schema/validation"
import "./schema/metadata"
import "./schema/reviewer"
import "./schema/upload"
import "./schema/worker"
import "./schema/misc"
import "./schema/permissions"
import "./schema/user"
import "./schema/comment"
import "./schema/dataset-events"
import "./schema/draft"
import "./schema/snapshot"
import "./schema/dataset"
import "./schema/dataset-search"
import "./schema/query"
import "./schema/mutation"

export default builder.toSchema()
