/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ResourceTypeGeneral =
  | "Audiovisual"
  | "Book"
  | "BookChapter"
  | "Collection"
  | "ComputationalNotebook"
  | "ConferencePaper"
  | "ConferenceProceeding"
  | "DataPaper"
  | "Dataset"
  | "Dissertation"
  | "Event"
  | "Image"
  | "Instrument"
  | "InteractiveResource"
  | "Journal"
  | "JournalArticle"
  | "Model"
  | "OutputManagementPlan"
  | "PeerReview"
  | "PhysicalObject"
  | "Preprint"
  | "Report"
  | "Service"
  | "Software"
  | "Sound"
  | "Standard"
  | "StudyRegistration"
  | "Text"
  | "Workflow"
  | "Other"
export type Creator = Person
export type NameType = "Organizational" | "Personal"
export type NameIdentifiers = {
  nameIdentifier: string
  nameIdentifierScheme: string
  schemeUri?: string
}[]
export type Affiliation = {
  name: string
  affiliationIdentifier?: string
  affiliationIdentifierScheme?: string
  schemeUri?: string
}[]
export type TitleType =
  | "AlternativeTitle"
  | "Subtitle"
  | "TranslatedTitle"
  | "Other"
export type PublicationYear = string
export type Contributor = Person & {
  contributorType: ContributorType
  [k: string]: unknown
}
export type ContributorType =
  | "ContactPerson"
  | "DataCollector"
  | "DataCurator"
  | "DataManager"
  | "Distributor"
  | "Editor"
  | "HostingInstitution"
  | "Producer"
  | "ProjectLeader"
  | "ProjectManager"
  | "ProjectMember"
  | "RegistrationAgency"
  | "RegistrationAuthority"
  | "RelatedPerson"
  | "Researcher"
  | "ResearchGroup"
  | "RightsHolder"
  | "Sponsor"
  | "Supervisor"
  | "WorkPackageLeader"
  | "Other"
export type Date = {
  [k: string]: unknown
}
export type Date1 = string
export type DateType =
  | "Accepted"
  | "Available"
  | "Copyrighted"
  | "Collected"
  | "Created"
  | "Issued"
  | "Submitted"
  | "Updated"
  | "Valid"
  | "Withdrawn"
  | "Other"
export type RelationType =
  | "IsCitedBy"
  | "Cites"
  | "IsCollectedBy"
  | "Collects"
  | "IsSupplementTo"
  | "IsSupplementedBy"
  | "IsContinuedBy"
  | "Continues"
  | "IsDescribedBy"
  | "Describes"
  | "HasMetadata"
  | "IsMetadataFor"
  | "HasVersion"
  | "IsVersionOf"
  | "IsNewVersionOf"
  | "IsPartOf"
  | "IsPreviousVersionOf"
  | "IsPublishedIn"
  | "HasPart"
  | "IsReferencedBy"
  | "References"
  | "IsDocumentedBy"
  | "Documents"
  | "IsCompiledBy"
  | "Compiles"
  | "IsVariantFormOf"
  | "IsOriginalFormOf"
  | "IsIdenticalTo"
  | "IsReviewedBy"
  | "Reviews"
  | "IsDerivedFrom"
  | "IsSourceOf"
  | "IsRequiredBy"
  | "Requires"
  | "IsObsoletedBy"
  | "Obsoletes"
export type DescriptionType =
  | "Abstract"
  | "Methods"
  | "SeriesInformation"
  | "TableOfContents"
  | "TechnicalInfo"
  | "Other"
export type Longitude = number
export type Latitude = number
export type FunderIdentifierType =
  | "ISNI"
  | "GRID"
  | "Crossref Funder ID"
  | "ROR"
  | "Other"

/**
 * JSON representation of the DataCite v4.5 schema.
 */
export interface DataCiteV45 {
  doi?: string
  prefix?: string
  suffix?: string
  event?: "hide" | "register" | "publish"
  url?: string
  types: {
    resourceType?: string
    resourceTypeGeneral: ResourceTypeGeneral
  }
  /**
   * @minItems 1
   */
  creators: [Creator, ...Creator[]]
  /**
   * @minItems 1
   */
  titles: [
    {
      title: string
      titleType?: TitleType
      lang?: string
    },
    ...{
      title: string
      titleType?: TitleType
      lang?: string
    }[],
  ]
  publisher: {
    name: string
    publisherIdentifier?: string
    publisherIdentifierScheme?: string
    schemeUri?: string
    lang?: string
  }
  publicationYear: PublicationYear
  subjects?: {
    subject: string
    subjectScheme?: string
    schemeUri?: string
    valueUri?: string
    classificationCode?: string
    lang?: string
  }[]
  contributors?: Contributor[]
  dates?: {
    date: Date & Date1
    dateType: DateType
    dateInformation?: string
  }[]
  language?: string
  alternateIdentifiers?: {
    alternateIdentifier: string
    alternateIdentifierType: string
  }[]
  relatedIdentifiers?: RelatedObject[]
  relatedItems?: RelatedObject[]
  sizes?: string[]
  formats?: string[]
  version?: string
  rightsList?: {
    rights?: string
    rightsUri?: string
    rightsIdentifier?: string
    rightsIdentifierScheme?: string
    schemeUri?: string
    lang?: string
  }[]
  descriptions?: {
    description: string
    descriptionType: DescriptionType
    lang?: string
  }[]
  geoLocations?: {
    geoLocationPlace?: string
    geoLocationPoint?: GeoLocationPoint
    geoLocationBox?: {
      westBoundLongitude: Longitude
      eastBoundLongitude: Longitude
      southBoundLatitude: Latitude
      northBoundLatitude: Latitude
    }
    geoLocationPolygon?: {
      polygonPoint?: GeoLocationPoint
      inPolygonPoint?: GeoLocationPoint
    }[]
  }[]
  fundingReferences?: {
    funderName: string
    funderIdentifier?: string
    funderIdentifierType?: FunderIdentifierType
    awardNumber?: string
    awardUri?: string
    awardTitle?: string
  }[]
  schemaVersion: "http://datacite.org/schema/kernel-4"
  container?: {
    type?: string
    title?: string
    firstPage?: string
    [k: string]: unknown
  }
}
export interface Person {
  name: string
  nameType?: NameType
  givenName?: string
  familyName?: string
  nameIdentifiers?: NameIdentifiers
  affiliation?: Affiliation
  lang?: string
  [k: string]: unknown
}
export interface RelatedObject {
  relationType: RelationType
  relatedMetadataScheme?: string
  schemeUri?: string
  schemeType?: string
  resourceTypeGeneral?: ResourceTypeGeneral
  [k: string]: unknown
}
export interface GeoLocationPoint {
  pointLongitude: Longitude
  pointLatitude: Latitude
}
