apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-scheduler
  labels:
    app: {{ .Release.Name }}-scheduler
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-scheduler
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-scheduler
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Release.Name }}-scheduler
          image: 'openneuro/datalad-service:v{{ .Chart.AppVersion }}'
          command: ['taskiq', 'scheduler', 'datalad_service.broker.scheduler:scheduler', '--tasks-pattern', 'datalad_service/tasks/*.py', '--fs-discover']
          resources:
            requests:
              cpu: {{ .Values.workerCpuRequests }}
              memory: {{ .Values.workerMemoryRequests }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
            - secretRef:
                name: {{ .Release.Name }}-secret
