apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-indexer
  labels:
    app: {{ .Release.Name }}-indexer
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
spec:
  schedule: "57 */4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: openneuro-indexer
            image: 'openneuro/indexer:v{{ .Chart.AppVersion }}'
            resources:
              limits:
                cpu: ".5"
                memory: "2048Mi"
              requests:
                cpu: ".5"
                memory: "2048Mi"
            env:
              - name: NODE_OPTIONS
                value: '--max_old_space_size=2048'
            envFrom:
              - configMapRef:
                  name: {{ .Release.Name }}-configmap
              - secretRef:
                  name: {{ .Release.Name }}-secret
          restartPolicy: OnFailure
