apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
stringData:
  JWT_SECRET: {{ required "JWT_SECRET is required" .Values.secrets.JWT_SECRET | quote }}
{{- if .Values.secrets.auth.GOOGLE_CLIENT_SECRET }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.auth.GOOGLE_CLIENT_ID | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.auth.GOOGLE_CLIENT_SECRET | quote }}
{{- end }}
{{- if .Values.secrets.auth.ORCID_CLIENT_SECRET }}
  ORCID_CLIENT_ID: {{ .Values.secrets.auth.ORCID_CLIENT_ID | quote }}
  ORCID_CLIENT_SECRET: {{ .Values.secrets.auth.ORCID_CLIENT_SECRET | quote }}
  ORCID_API_ENDPOINT: {{ .Values.secrets.auth.ORCID_API_ENDPOINT | quote }}
{{- end }}
{{- if .Values.secrets.auth.GLOBUS_CLIENT_SECRET }}
  GLOBUS_CLIENT_ID: {{ .Values.secrets.auth.GLOBUS_CLIENT_ID | quote }}
  GLOBUS_CLIENT_SECRET: {{ .Values.secrets.auth.GLOBUS_CLIENT_SECRET | quote }}
{{- end }}
  CRN_SERVER_MAIL_SERVICE: {{ required "MAIL_SERVICE is required" .Values.secrets.mail.CRN_SERVER_MAIL_SERVICE | quote }}
  CRN_SERVER_MAIL_USER: {{ required "MAIL_USER is required" .Values.secrets.mail.CRN_SERVER_MAIL_USER | quote }}
  CRN_SERVER_MAIL_URL: {{ required "MAIL_URL is required" .Values.secrets.mail.CRN_SERVER_MAIL_USER | quote }}
  CRN_SERVER_MAIL_PASS: {{ required "MAIL_PASS is required" .Values.secrets.mail.CRN_SERVER_MAIL_USER | quote }}
  AWS_REGION: {{ required "AWS_REGION is required" .Values.secrets.aws.AWS_REGION | quote }}
  AWS_ACCOUNT_ID: {{ required "AWS_ACCOUNT_ID is required" .Values.secrets.aws.AWS_ACCOUNT_ID | quote }}
  AWS_ACCESS_KEY_ID: {{ required "AWS_ACCESS_KEY_ID is required" .Values.secrets.aws.AWS_ACCESS_KEY_ID | quote }}
  AWS_SECRET_ACCESS_KEY: {{ required "AWS_SECRET_ACCESS_KEY is required" .Values.secrets.aws.AWS_SECRET_ACCESS_KEY | quote }}
  AWS_S3_PRIVATE_BUCKET: {{ required "AWS_REGION is required" .Values.secrets.aws.AWS_S3_PRIVATE_BUCKET | quote }}
  AWS_S3_PUBLIC_BUCKET: {{ required "AWS_REGION is required" .Values.secrets.aws.AWS_S3_PUBLIC_BUCKET | quote }}
  DATALAD_GITHUB_EXPORTS_ENABLED: {{ default true .Values.secrets.datalad.DATALAD_GITHUB_EXPORTS_ENABLED | quote }}
  DATALAD_GITHUB_LOGIN: {{ .Values.secrets.datalad.DATALAD_GITHUB_LOGIN | quote }}
  DATALAD_GITHUB_ORG: {{ .Values.secrets.datalad.DATALAD_GITHUB_ORG | quote }}
  DATALAD_GITHUB_PASS: {{ .Values.secrets.datalad.DATALAD_GITHUB_PASS | quote }}
  DOI_USERNAME: {{ required "DOI_USERNAME is required" .Values.secrets.doi.DOI_USERNAME | quote }}
  DOI_PASSWORD: {{ required "DOI_PASSWORD is required" .Values.secrets.doi.DOI_PASSWORD | quote }}
  DOI_PREFIX: {{ required "DOI_PREFIX is required" .Values.secrets.doi.DOI_PREFIX | quote }}
  DOI_URL: {{ required "DOI_URL is required" .Values.secrets.doi.DOI_URL | quote }}
  FLOWER_BASIC_AUTH: {{ required "FLOWER_BASIC_AUTH must be set to avoid insecure default values" .Values.secrets.flower.FLOWER_BASIC_AUTH | quote }}
  MONGO_URL: {{ required "MONGO_URL with credentials is required" .Values.secrets.mongo.MONGO_URL | quote }}
  ENGINE_API_KEY: {{ .Values.secrets.apollo.ENGINE_API_KEY | quote }}
