---
name: Deno build

on:
  push:
    branches: [master]
    tags: ['*']
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
      fail-fast: false
    defaults:
      run:
        working-directory: ./cli
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1.1.2
        with:
          deno-version: v1.x
      - name: Collect coverage
        run: deno task coverage
        if: ${{ always() }}
      - uses: codecov/codecov-action@v4
        if: ${{ always() }}
        with:
          files: coverage.lcov
