name: Python tests and coverage

on:
  push: { branches: [master] }
  pull_request: { branches: [master] }

defaults:
  run:
    working-directory: ./services/datalad

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.13 (uv)
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: "3.13"
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Setup Deno stable
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install git-annex
        run: uv tool install git-annex
      - name: Install dependencies
        run: uv sync --locked --dev
      - name: Configure git defaults
        run: |
          git config --global user.name "Git Worker"
          git config --global user.email "ci@openneuro.org"
          git config --global receive.denyCurrentBranch updateInstead
      - name: Run tests and collect coverage
        run: uv run pytest -n 4 --cov=./datalad_service --cov-report=xml:coverage.xml ./tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
